name: Build
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions-rs/toolchain@v1.0.6
        with: 
          toolchain: stable-gnu
          profile: minimal
          default: true
      - uses: actions/checkout@v2
      - name: Enable static CRT linkage
        run: |
          mkdir .cargo
          echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
          echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
      - name: Build binary
        run: |
          cargo build --verbose --release
          VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml)
          cp target/release/bitwarden-autotype.exe bitwarden-autotype-$VERSION.exe
      - name: Create installer
        run: iscc bitwarden-autotype.iss
      - name: Generate checksums
        run: |
          for f in bitwarden-autotype*.exe; do
            powershell -c "Get-FileHash $f | Select-Object -ExpandProperty Hash" > $f.sha256
          done
      - name: Archive binary
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: |
            bitwarden-autotype*.exe*
      - name: Release binary
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: bitwarden-autotype*.exe*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
